# Generated by Django 4.2.21 on 2025-09-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_service_description_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service'), ('part', 'Part'), ('labor', 'Labor'), ('other', 'Other')], default='service', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='part_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
