# Generated by Django 5.2.6 on 2025-11-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_item_type_and_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('quotation', 'Quotation')], default='invoice', max_length=20),
        ),
    ]
