# Generated by Django 4.2.21 on 2025-09-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('preferred_contact', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_service_date', models.DateTimeField(blank=True, null=True)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.TextField(blank=True)),
            ],
        ),
    ]
