# Generated by Django 4.2.21 on 2025-09-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='future',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='previous',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='products_supplied',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(default='due', max_length=50),
        ),
    ]
