# Generated by Django 4.2.21 on 2025-09-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_amount_supplier_due_date_supplier_future_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
