# Generated by Django 4.2.21 on 2025-09-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplier_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='goods_supplier',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
