# Generated by Django 4.2.21 on 2025-09-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_supplier_goods_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='inventory_sold',
            field=models.TextField(blank=True),
        ),
    ]
