# Generated by Django 4.2.21 on 2025-09-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_amount_supplier_due_date_supplier_future_and_more'),
        ('sales', '0002_add_walk_in_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='inventory.supplier'),
        ),
    ]
