# Generated by Django 4.2.21 on 2025-09-08 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_technicianprofile_technicianmessage_partsrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
