# Generated by Django 4.2.21 on 2025-09-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_technician_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('ready_to_collect', 'Ready to Collect'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='pending', max_length=20),
        ),
    ]
