# Generated by Django 4.2.21 on 2025-09-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department'),
        ('jobs', '0005_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='api.department'),
        ),
    ]
